apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: karanj01/techtrends:latest
        name: techtrends
        ports:
        - containerPort: 3111
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
            httpHeaders:
            - name: Custom-Header
              value: Status
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
            httpHeaders:
            - name: Custom-Header
              value: Status
          initialDelaySeconds: 10
          periodSeconds: 10          
